name: trabalho_bd
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  postgres: ^3.5.6
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  mime: ^1.0.6
  url_launcher: ^6.3.1
  intl: ^0.20.2
  crypto: ^3.0.3
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/sql/schema.sql